apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube
  labels:
    app: minikube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minikube
  template:
    metadata:
      labels:
        app: minikube
    spec:
      containers:
      - name: minikube
        image: gcr.io/k8s-minikube/kicbase:v0.0.45  # Reemplaza con tu imagen personalizada
        ports:
        - containerPort: 8080
